# post 
###
POST http://localhost:8080/api/expense
Content-Type: application/json

{
    "title":"es teh",
    "amount": 5000,
    "category": "minuman",
    "date": "2025-06-28"
}


# get all
###
GET http://localhost:8080/api/expense


# get by id
###
GET http://localhost:8080/api/expense/3